# Generated by Django 5.1 on 2024-08-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicalData',
            new_name='ClincalData',
        ),
    ]
